# chche 用来指定需要在 builds 之间进行缓存的一组文件、文件夹。 你可以只使用project workspace里面的路径
cache:
  paths:
  - node_modules/

stages:
  - 部署

before_script:
  - export PATH=$(npm bin):$PATH
  - git config --global push.default simple
  - git remote set-url --push origin ${GIT_ADDRESS}/enterprise/dll.git
  - if [ ! -d "node_modules" ]; then yarn; else dm update; fi
  - node build/createDynamicID.js ${CI_COMMIT_SHA}

开发环境部署:
  stage: 部署
  when: manual
  tags:
    - dianmi-fe-enterprise-dll
  only:
    - branches
  environment:
    name: dev
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
    - dist/
    - package.json
    - common/
    - yarn.lock
  script:
    - dm upgrade -t alpha --dev --dev 
    - ${BUILD_SUBSYS_DEV}
    - ${DEPLOY_CDN_PD}
    - ${DEPLOY_NPM_DEV}

测试环境部署:
  stage: 部署
  when: manual
  tags:
    - dianmi-fe-enterprise-dll
  only:
    - branches
  environment:
    name: test
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
    - dist/
    - package.json
    - common/
    - yarn.lock
  script:
    - dm upgrade -t beta --dev --dev 
    - ${BUILD_SUBSYS_TEST}
    - ${DEPLOY_CDN_PD}
    - ${DEPLOY_NPM_TEST}

灰度环境部署:
  stage: 部署
  when: manual
  tags:
    - dianmi-fe-enterprise-dll
  only:
    - branches
  environment:
    name: uat
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
    - dist/
    - package.json
    - common/
    - yarn.lock
  script:
    - dm upgrade -t rc --dev --dev 
    - ${BUILD_SUBSYS_UAT}
    - ${DEPLOY_CDN_PD}
    - ${DEPLOY_NPM_UAT}

线上环境部署:
  stage: 部署
  when: manual
  tags:
    - dianmi-fe-enterprise-dll
  only:
    - branches
  environment:
    name: pd
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
    - dist/
    - package.json
    - common/
    - yarn.lock
  script:
    - dm upgrade -t latest --dev --dev 
    - ${BUILD_SUBSYS_PD}
    - ${DEPLOY_CDN_PD}
    - ${DEPLOY_NPM_PD}
